// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";

/**
 * @title ProxyHelper
 * @dev This contract exists solely to ensure that the ERC1967Proxy artifact 
 * is generated by Hardhat during compilation for use in tests.
 */
contract ProxyHelper {
    // No logic needed
}
